

create table T_Users(
    usrID NUMBER(4) ,
    empID VARCHAR2(17) UNIQUE,
    username varchar2(50)UNIQUE NOT NULL,
    psswrd varchar2(255) UNIQUE NOT NULL,
    usrEml VARCHAR2(255) UNIQUE NOT NULL,
    usrPhn NUMBER(10)UNIQUE NOT NULL,
    usrRole VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_USR PRIMARY KEY(usrID)
);

CREATE TABLE T_log_active (
    logID NUMBER (10),
    usrID NUMBER(4) NOT NULL,
    action_type VARCHAR2(50) NOT NULL,
    action_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    ip_address VARCHAR2(45),
        CONSTRAINT PK_LOG PRIMARY KEY(logID)
);

CREATE TABLE T_Requests (
    reqID NUMBER(8),
    usrID NUMBER(4)  ,   
    empID VARCHAR2(17),   
    typReq VARCHAR2(20) NOT NULL,  
    notReq VARCHAR2(255),           
    rsnReq VARCHAR2(500),          
    file_path VARCHAR2(255),  
    sttReq VARCHAR2(20) DEFAULT 'Pending',  
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
    CONSTRAINT Pk_REQ PRIMARY KEY(reqID)
);

CREATE TABLE T_Notifications (
    notID NUMBER (5),
    usrID NUMBER(4)  NOT NULL  ,  
    msg VARCHAR2(500),  
    status VARCHAR2(10) DEFAULT 'Unread', 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
    CONSTRAINT PK_NOT PRIMARY KEY(notID)
);

CREATE TABLE T_folders (
    fldrID VARCHAR2(17),
    empID VARCHAR2(17) UNIQUE NOT NULL ,
    fldr_path VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE T_employees (
    empID VARCHAR2(17),
    frstNmEmp VARCHAR2(50) NOT NULL ,
    lstNmEmp  VARCHAR2(50) NOT NULL,
    gndEmp CHAR(1) NOT NULL,
    empDatBrth DATE NOT NULL,
    munpBrth  VARCHAR2(50) NOT NULL,
    sttBrth VARCHAR2(50) NOT NULL,
    NatEmp  VARCHAR2(15) DEFAULT 'Algerian',
    socSecNum VARCHAR2(12) NOT NULL  UNIQUE,
    BnkAccNum VARCHAR2(13) NOT NULL UNIQUE,
    natSerCrdNum VARCHAR2(12) UNIQUE,
    natIdnCrdNum  VARCHAR2(9) NOT NULL UNIQUE,

    currAddrs VARCHAR2(255) NOT NULL,
    phoNum  VARCHAR2(10)NOT NULL UNIQUE,
    emlEmp  VARCHAR2(255) NOT NULL UNIQUE, -- 100

    famstt VARCHAR2(50) NOT NULL,
    husNm VARCHAR2(50) ,
    husFmNm VARCHAR2(50) ,
    numChd NUMBER(2) DEFAULT  0,

    workRel  VARCHAR2(20)NOT NULL,
    yrApp NUMBER(4) DEFAULT  EXTRACT(YEAR FROM SYSDATE),

    DepID VARCHAR2(10)  NOT Null,
    secID  VARCHAR2(10)  NOT Null,
    rnkID  VARCHAR2(10)  NOT Null,
    
    CONSTRAINT PK_EMP PRIMARY KEY(empID)
);

CREATE TABLE T_Emp_certificates (
    cerID VARCHAR2(8),
    empID VARCHAR2(17) UNIQUE, 
    CONSTRAINT PK_CER PRIMARY KEY(cerID)
)


CREATE TABLE T_Departments (
    DepID VARCHAR2(10),
    depName VARCHAR2(100)UNIQUE  NOT Null,
    depCode VARCHAR2(5) UNIQUE NOT Null,
    CONSTRAINT  PK_DEP PRIMARY KEY(DepID) 
);


CREATE TABLE T_Sectors (
    secID  VARCHAR2(10),
    secName  VARCHAR2(100) UNIQUE  NOT Null,
    secCode  VARCHAR2(5) UNIQUE  NOT Null,
    CONSTRAINT  PK_SEC PRIMARY KEY(secID) 
);

CREATE TABLE T_Ranks(
    rnkID  VARCHAR2(10),
    rnkName  VARCHAR2(150) UNIQUE NOT Null,
    rnkCode VARCHAR2(5) UNIQUE NOT Null,
    secID  VARCHAR2(8) NOT NULL,
    CONSTRAINT  PK_RNK PRIMARY KEY(rnkID)
);

CREATE TABLE T_Leaves (
    lvsID VARCHAR2(8), 
    lvstyp VARCHAR2(20) NOT NULL, 
    lvsReas VARCHAR2(20) NOT NULL ,
    lvsDur NUMBER(3) NOT NULL, 
    lvsStrtDat DATE NOT NULL,
    lvsEndDat DATE NOT NULL, 
    lvsStts VARCHAR2(50) DEFAULT 'Not Ended' NOT NULL, 
    empID VARCHAR2(17), 
    CONSTRAINT  PK_LVS PRIMARY KEY(lvsID)
);



CREATE TABLE T_transfers(
    traID VARCHAR2(8) ,
    currWrkp VARCHAR2(150) NOT NULL,
    orgDepAppDat DATE NOT NULL,
    recDepAppDat DATE NOT NULL, 
    newWrkStrDat DATE NOT NULL, 
    empID VARCHAR2(17)NOT NULL,
    DepID VARCHAR2(10),
    CONSTRAINT PK_TRNSFR PRIMARY KEY(traID)
);

CREATE TABLE T_resignations(
    resgID VARCHAR2(8),
    empConfDat DATE NOT NULL,
    resgRreas VARCHAR2(255),
    resgEffDat DATE NOT NULL,
    empID VARCHAR2(17) UNIQUE,
    CONSTRAINT PK_RESG PRIMARY KEY(resgID)
);

CREATE TABLE T_Retirement(
    retID VARCHAR2(8),
    empID VARCHAR2(17) NOT NULL UNIQUE,
    retReas VARCHAR2(50) NOT NULL,
    reqDat DATE NOT NULL,
    appDat DATE NOT NULL,
    CONSTRAINT PK_RET PRIMARY KEY(retID)
);
 



ALTER TABLE T_Users ADD CONSTRAINT FK_USR_EMP foreign key (empID) references T_employees(empID) ON DELETE CASCADE;

ALTER TABLE T_log_active ADD CONSTRAINT FK_USR_LOG FOREIGN KEY (usrID) REFERENCES T_Users(usrID) ON DELETE CASCADE;

ALTER TABLE T_Requests ADD CONSTRAINT FK_EMP_REQ foreign key (empID) references T_employees(empID) ON DELETE CASCADE;

ALTER TABLE T_Requests ADD CONSTRAINT FK_USR_REQ foreign key (usrID) references T_Users(usrID) ON DELETE CASCADE;

ALTER TABLE T_Notifications ADD CONSTRAINT FK_NOT_USR foreign key (usrID) references T_Users(usrID) ON DELETE CASCADE;

ALTER TABLE   T_folders ADD CONSTRAINT FK_EMP foreign key (empID) references T_employees(empID) ON DELETE CASCADE ; 
ALTER TABLE  T_employees ADD CONSTRAINT FK_DEP foreign key (DepID) references T_Departments(DepID) ON DELETE CASCADE; --1
ALTER TABLE  T_employees ADD CONSTRAINT FK_SEC_EMP foreign key (secID) references T_Sectors(secID) ON DELETE CASCADE; -- 2
ALTER TABLE  T_employees ADD CONSTRAINT FK_RNK foreign key (rnkID) references T_Ranks(rnkID)ON DELETE CASCADE; --3
ALTER TABLE T_Emp_certificates ADD CONSTRAINT FK_EMP_CER foreign key (empID) references T_employees(empID)ON DELETE CASCADE;
ALTER TABLE T_Ranks ADD CONSTRAINT FK_SEC foreign key (secID) references T_Sectors(secID)ON DELETE CASCADE;
ALTER TABLE T_Leaves ADD CONSTRAINT FK_LVS_EMP foreign key (empID) references T_employees(empID)ON DELETE CASCADE;
ALTER TABLE T_Transfers ADD CONSTRAINT FK_TRN_DEP foreign key (DepID) references T_Departments(DepID)ON DELETE CASCADE;
ALTER TABLE T_resignations ADD CONSTRAINT FK_RESG_EMP foreign key (empID) references T_employees(empID)ON DELETE CASCADE;
ALTER TABLE  T_Retirement ADD CONSTRAINT FK_RET_EMP foreign key (empID) references  T_employees(empID)ON DELETE CASCADE;








CREATE SEQUENCE SEQ_USR
START WITH 1000
INCREMENT by 1
NOCACHE;


CREATE SEQUENCE SEQ_EMP
START WITH 1000
INCREMENT by 1
NOCACHE;

CREATE SEQUENCE SEQ_DEP
START WITH 100
INCREMENT by 1
NOCACHE;

CREATE SEQUENCE SEQ_SEC
START WITH 100
INCREMENT by 1
NOCACHE;

CREATE SEQUENCE SEQ_RNK
START WITH 100
INCREMENT by 1
NOCACHE;

CREATE SEQUENCE SEQ_CER
START WITH 100
INCREMENT by 1
NOCACHE;

CREATE SEQUENCE SEQ_LVS
START WITH 100
INCREMENT by 1
NOCACHE;

CREATE SEQUENCE SEQ_TRN
START WITH 100
INCREMENT by 1
NOCACHE;
 
CREATE SEQUENCE SEQ_RESG
START WITH 100
INCREMENT by 1
NOCACHE;


CREATE SEQUENCE SEQ_RET
START WITH 100
INCREMENT by 1
NOCACHE;

CREATE SEQUENCE SEQ_FLD
START WITH 100
INCREMENT by 1
NOCACHE;

CREATE SEQUENCE SEQ_REQ
START WITH 100
INCREMENT by 1
NOCACHE;


CREATE SEQUENCE SEQ_NOT
START WITH 100
INCREMENT by 1
NOCACHE;
 
CREATE SEQUENCE SEQ_LOG
START WITH 100
INCREMENT by 1
NOCACHE;
 
 commit;



 
